# Permalinks
permalink:           /blog/:title/

# Setup
title:               Aerosailor
url:                 http://aerosailor.com
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  load-paths:
    - _sass
    - node_modules
  style:            :compressed

# fonts:
  # url: https://fonts.googleapis.com/css?family=Montserrat:300,700

# About/contact
author:
  name:              Meher Ranjan Howji
  url:               https://aeosailor.com
  email:             mail@aerosailor.com
  aboutme:           I am Meher Ranjan Howji. I work with Credit Suisse in Pune. I am passionate about JavaScript, React and Elm. Exploring ReasonML and bunch of stuff around machine learning.
  location:          Pune, India

# Custom vars
version:             1.1
analytics_id:        UA-116074903-1
github:
  repo:              https://github.com/meherranjan

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-admin
  - jemoji

exclude: [package.json, deploy.sh, yarn.lock, README.md, LICENSE.md, scripts]
keep_files: [scripts/bundle.js, public/assets/emoji]
livereload: true